version: '3.7'

networks:
  dev:
    driver: bridge

services:
  db:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - dev

  # app:
  #   build: .
  #   container_name: app
  #   restart: always
  #   environment:
  #     DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
  #   volumes:
  #     - .:/app
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - dev
  #   depends_on:
  #     - db